name = "BigGold"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f1347a9eb5c44eec40561225124fbd2788d6b467b426b36cc1c6094b7faa064"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
