name = "BigGold"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8396afe6bd4d40fe87afa00c8141327f31dc38d3dffcb55eee3698c801e2c31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
